/**
 * Demo payloads used ONLY when the /api/dsh-literature route family is
 * unreachable in a development build. They mirror the wire shapes, and the
 * workbench always labels this source "Demo". Production never imports these
 * values as a fallback for unavailable live data.
 */
import type { UiDashboard, UiPaperDetail, UiPaperSummary, UiPushStatus } from './wire.ts'

export const MOCK_PAPERS: UiPaperSummary[] = [
  {
    id: 'arxiv:2301.04142',
    title: 'Learning Robust Perceptive Locomotion for Quadrupedal Robots in the Wild',
    authors: ['Fabian Jenelten', 'Junzhe He', 'Firas Farshidian', 'Marco Hutter'],
    year: 2023,
    venue: 'arXiv preprint',
    doi: '10.48550/arXiv.2301.04142',
    citations: 128,
    agentRank: 1,
    finalScore: 0.91,
    selected: true,
    hasPdf: true,
    readCount: 12,
    reportCount: 1,
    topic: '足式机器人控制',
    createdAt: '2026-08-01 09:00:00',
  },
  {
    id: 'arxiv:2110.00195',
    title: 'Perceptive Locomotion through Nonlinear Model-Predictive Control',
    authors: ['Ruben Grandia', 'Fabian Jenelten', 'Shaojie Yang', 'Firas Farshidian', 'Marco Hutter'],
    year: 2021,
    venue: 'IEEE Transactions on Robotics',
    doi: '10.1109/TRO.2022.3197645',
    citations: 94,
    agentRank: 2,
    finalScore: 0.87,
    selected: true,
    hasPdf: true,
    readCount: 8,
    reportCount: 1,
    topic: '足式机器人控制',
    createdAt: '2026-07-28 09:00:00',
  },
  {
    id: 'arxiv:2201.02422',
    title: 'Rapid Locomotion via Reinforcement Learning',
    authors: ['Gabriel B. Margolis', 'Ge Yang', 'Kangcheng Paigwar', 'Tao Chen', 'Xiangyun Ji'],
    year: 2022,
    venue: 'arXiv preprint',
    doi: '10.48550/arXiv.2201.02422',
    citations: 61,
    agentRank: 3,
    finalScore: 0.84,
    selected: true,
    hasPdf: true,
    readCount: 6,
    reportCount: 1,
    topic: '足式机器人控制',
    createdAt: '2026-07-20 09:00:00',
  },
  {
    id: 'arxiv:1901.08152',
    title: 'Anymal — a highly mobile and dynamic quadrupedal robot',
    authors: ['Marco Hutter', 'Christian Gehring', 'Dominic Jud', 'Andreas Lauber'],
    year: 2016,
    venue: 'IEEE/RSJ IROS',
    doi: '10.1109/IROS.2016.7758092',
    citations: 210,
    agentRank: 4,
    finalScore: 0.79,
    selected: false,
    hasPdf: false,
    readCount: 0,
    reportCount: 0,
    topic: '足式机器人控制',
    createdAt: '2026-07-15 09:00:00',
  },
  {
    id: 'doi:10.1177/02783640122067309',
    title: 'Virtual Model Control: An Intuitive Approach for Bipedal Locomotion',
    authors: ['Jerry Pratt', 'Chee-Meng Chew', 'Ann Torres', 'Peter Dilworth', 'Gill Pratt'],
    year: 2001,
    venue: 'The International Journal of Robotics Research',
    doi: '10.1177/02783640122067309',
    citations: 540,
    agentRank: null,
    finalScore: null,
    selected: false,
    hasPdf: true,
    readCount: 4,
    reportCount: 0,
    topic: '足式机器人控制',
    createdAt: '2026-06-30 09:00:00',
  },
  {
    id: 'doi:10.1109/ROBOT.2006.1641685',
    title: 'Capture Point: A Step toward Humanoid Push Recovery',
    authors: ['Jerry Pratt', 'John Carff', 'Sergey Drakunov', 'Ambarish Goswami'],
    year: 2006,
    venue: 'IEEE ICRA',
    doi: '10.1109/ROBOT.2006.1641685',
    citations: 480,
    agentRank: null,
    finalScore: null,
    selected: false,
    hasPdf: false,
    readCount: 0,
    reportCount: 0,
    topic: '足式机器人控制',
    createdAt: '2026-06-25 09:00:00',
  },
  {
    id: 'openalex:W2887048226',
    title: 'Model Predictive Control for Legged Robots',
    authors: ['Yanran Ding', 'Abhishek Pandala', 'Huawei Liang'],
    year: 2019,
    venue: 'arXiv preprint',
    doi: '10.48550/arXiv.1901.09622',
    citations: 150,
    agentRank: 5,
    finalScore: 0.72,
    selected: false,
    hasPdf: false,
    readCount: 0,
    reportCount: 0,
    topic: '足式机器人控制',
    createdAt: '2026-06-20 09:00:00',
  },
  {
    id: 'arxiv:2407.07787',
    title: 'Whole-Body MPC and Online Gait Sequence Generation for Wheeled-Legged Robots',
    authors: ['Marko Bjelonic', 'Ruben Grandia', 'Marco Hutter'],
    year: 2024,
    venue: 'IEEE Transactions on Robotics',
    doi: '10.1109/TRO.2024.3399836',
    citations: 35,
    agentRank: null,
    finalScore: null,
    selected: false,
    hasPdf: false,
    readCount: 0,
    reportCount: 0,
    topic: '足式机器人控制',
    createdAt: '2026-06-12 09:00:00',
  },
]

const MOCK_DETAIL: UiPaperDetail = {
  ...MOCK_PAPERS[0]!,
  researchFields: [
    { id: 1, slug: 'robotics', nameEn: 'Robotics', nameZh: '机器人学', source: 'auto' },
    { id: 4, slug: 'control', nameEn: 'Control', nameZh: '控制', source: 'manual' },
  ],
  abstract: 'We present a robust and perceptive locomotion policy for quadrupedal robots navigating in the wild. The policy is trained in simulation with domain randomization and deployed zero-shot on a real robot, showing recovery from perturbations and traversal of rough terrain.',
  arxivId: '2301.04142',
  openalexId: 'W4281950083',
  url: 'https://arxiv.org/abs/2301.04142',
  oaPdfUrl: 'https://arxiv.org/pdf/2301.04142',
  bibtex: '@article{jenelten2023learning,\n  title={Learning Robust Perceptive Locomotion for Quadrupedal Robots in the Wild},\n  author={Jenelten, Fabian and He, Junzhe and Farshidian, Firas and Hutter, Marco},\n  year={2023}\n}',
  metadataSource: 'arxiv',
  selectionReason: 'Representative sim-to-real perceptive locomotion; strong stage relevance for RL locomotion stage.',
  stage: 1,
  selectionOutcome: 'SELECTED',
  acquisitionOutcome: 'SELECTED',
  acquisitionReason: 'arXiv open-access PDF',
  fulltextStatus: 'ok',
  fulltextChunks: 14,
  readCoverage: 0.86,
  pdfPath: '~/.local/share/dsh-literature/pdfs/sha256abc.pdf',
  pdfSource: 'https://arxiv.org/pdf/2301.04142',
  accessType: 'oa',
  isOpenAccess: true,
  reportPath: '~/.local/share/dsh-literature/reports/基础控制/jenelten2023_learning_robust.md',
}

export const MOCK_DASHBOARD: UiDashboard = {
  paperCount: MOCK_PAPERS.length,
  pushCount: 17,
  reportCount: 3,
  categories: [
    { id: 'all', label: 'All Papers', kind: 'workflow', count: MOCK_PAPERS.length },
    { id: 'selected', label: 'Selected', kind: 'workflow', count: 3 },
    { id: 'read', label: 'Read', kind: 'workflow', count: 4 },
    { id: 'reports', label: 'Reports', kind: 'workflow', count: 3 },
    { id: 'favorites', label: 'Favorites', kind: 'workflow', count: 0 },
    { id: 'field:1', categoryId: 1, label: 'Robotics', labelEn: 'Robotics', labelZh: '机器人学', kind: 'field', count: 8, createdBy: 'system' },
    { id: 'field:2', categoryId: 2, label: 'Agricultural Robotics', labelEn: 'Agricultural Robotics', labelZh: '农业机器人', kind: 'field', count: 0, createdBy: 'system' },
    { id: 'field:3', categoryId: 3, label: 'Agricultural Engineering', labelEn: 'Agricultural Engineering', labelZh: '农业工程', kind: 'field', count: 0, createdBy: 'system' },
    { id: 'field:4', categoryId: 4, label: 'Control', labelEn: 'Control', labelZh: '控制', kind: 'field', count: 5, createdBy: 'system' },
    { id: 'field:5', categoryId: 5, label: 'Reinforcement Learning', labelEn: 'Reinforcement Learning', labelZh: '强化学习', kind: 'field', count: 3, createdBy: 'system' },
    { id: 'field:6', categoryId: 6, label: 'Soil & Water', labelEn: 'Soil & Water', labelZh: '土壤与水', kind: 'field', count: 0, createdBy: 'system' },
    { id: 'topic:足式机器人控制', label: '足式机器人控制', kind: 'topic', count: 8 },
  ],
  latestPush: { id: 17, status: 'running', topic: '足式机器人控制' },
  stages: [
    { topic: '足式机器人控制', current: 1, label: '基础控制', papersInStage: 3, targetPapers: 3 },
  ],
}

export const MOCK_PUSH_STATUS: UiPushStatus = {
  present: true,
  pushId: 17,
  phase: 'acquiring',
  label: 'ACQUIRING',
  rawStatus: 'running',
  topic: '足式机器人控制',
  stage: 1,
  stageLabel: '基础控制',
  startedAt: '2026-08-17 09:12:00',
  finishedAt: null,
  errorCode: null,
  errorDetail: null,
  running: true,
  retrieving: [
    { source: 'OpenAlex', retrievedAt: '2026-08-17 09:12:31' },
    { source: 'arXiv', retrievedAt: '2026-08-17 09:12:58' },
    { source: 'Crossref', retrievedAt: '2026-08-17 09:13:02' },
  ],
  retrievedPapers: 218,
  candidatesRanked: 15,
  acquisition: [
    {
      agentRank: 1,
      paperId: 'arxiv:2407.07787',
      title: 'Whole-Body MPC and Online Gait Sequence Generation for Wheeled-Legged Robots',
      publicPreflight: 'UNAVAILABLE',
      outcome: null,
      reason: null,
    },
  ],
  reading: { totalChunks: null, readChunks: null, coverage: null },
  reporting: { reportGenerationMs: null, reportPath: null },
  authRequired: null,
  notes: null,
  perf: { retrievalMs: 18400, rankingMs: 9200, totalMs: null, llmCallCount: 2 },
}

export const MOCK_AUTH_STATUS: UiPushStatus = {
  ...MOCK_PUSH_STATUS,
  phase: 'auth_required',
  label: 'AUTH_REQUIRED',
  rawStatus: 'auth_required',
  running: false,
  startedAt: '2026-08-16 09:12:00',
  acquisition: [
    {
      agentRank: 1,
      paperId: 'doi:10.1109/TRO.2024.3399836',
      title: 'Whole-Body MPC and Online Gait Sequence Generation for Wheeled-Legged Robots',
      publicPreflight: 'UNAVAILABLE',
      outcome: 'AUTH_REQUIRED',
      reason: 'IEEE login wall at https://ieeexplore.ieee.org/document/10514982',
    },
  ],
  authRequired: {
    paperTitle: 'Whole-Body MPC and Online Gait Sequence Generation for Wheeled-Legged Robots',
    publisher: 'IEEE (ieeexplore.ieee.org)',
    rank: 1,
    reason: 'Publisher login wall — needs institutional (CARSI / proxy) credentials.',
    nextStep: 'Complete a legal login in a headed browser, then Resume.',
    actions: [
      {
        id: 3,
        paperId: 'doi:10.1109/TRO.2024.3399836',
        paperTitle: 'Whole-Body MPC and Online Gait Sequence Generation for Wheeled-Legged Robots',
        step: 'fetch_pdf',
        kind: 'user_resource_needed',
        issue: 'IEEE login wall at https://ieeexplore.ieee.org/document/10514982',
        attempts: ['arXiv (no match)', 'Unpaywall (no OA)', 'publisher_browser (AUTH_REQUIRED)'],
        whatUserShouldDo: '登录 IEEE（机构访问），然后把 PDF 剪切进文献库后 Resume',
        howToContinue: '运行 dsh-literature-push.mjs --resume 17',
      },
    ],
  },
}

export function mockDetail(id: string): UiPaperDetail {
  const paper = MOCK_PAPERS.find((p) => p.id === id)
  if (paper === undefined) return MOCK_DETAIL
  return { ...MOCK_DETAIL, ...paper }
}
